# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

scan_timeout = 200
command_timeout = 1000

[aws]
disabled = true

[battery]
disabled = true

[cmd_duration]
disabled = true

[conda]
truncation_length = 0

[directory]
truncation_length = 13
truncate_to_repo = false

[hostname]
disabled = true

[python]
python_binary = ["python", "python3"]

[username]
disabled = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = false

[git_metrics]
disabled = false
added_style = 'bold green'
deleted_style = 'bold red'
only_nonzero_diffs = true
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'
ignore_submodules = false

[git_status]
disabled = false
